download_url_sample: "https://github.com/hartwigmedical/testdata/raw/refs/heads/master/cancerPanel/CPCT12345678R" #"https://osf.io/4rdza/download"
download_url_ref: "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/hg38Patch7/hg38Patch7.fa.gz" #"https://osf.io/8sm92/download"
download_lcr_url: "https://github.com/lh3/varcmp/raw/refs/heads/master/scripts/LCR-hs38.bed.gz"
download_dbsnp_url: "https://ftp.ncbi.nih.gov/snp/organisms/human_9606/VCF/00-common_all.vcf.gz"
download_dbsnp_tbi_url: "https://ftp.ncbi.nih.gov/snp/organisms/human_9606/VCF/00-common_all.vcf.gz.tbi"
tumor_normal_pairs:
  "SRR12300605_1": "SRR17674714_1"
  #"CPCT12345678R_AHHKYHDSXX_S13_L001_R1_001": "CPCT12345678R_HJJLGCCXX_S1_L001_R1_001"
  #"CPCT12345678R_AHHKYHDSXX_S13_L001_R2_001": "CPCT12345678R_HJJLGCCXX_S1_L001_R2_001"
raw_data_sample_dir: "raw_data/sample_data"
raw_data_ref_dir: "raw_data/ref_data"
fastqc_dir: "results/fastqc"
minimap_dir: "results/minimap"
picard_dir: "results/picard"
multiqc_dir: "results/multiqc"
gatk_dir: "results/gatk"